version: '3'

services:
  python:
    build:
      context: ./.docker/python/development
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    environment:
      - APP_NAME=movies
      
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_DATABASE_TEST=${DB_DATABASE_TEST}

      - KINOPOISK_TOKEN=${KINOPOISK_TOKEN}
  postgres:
    build:
      context: ./.docker/postgres/development
      dockerfile: Dockerfile
    volumes:
      - ./.docker/postgres/development:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: "${DB_DATABASE},${DB_DATABASE_TEST}"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "15432:5432"

volumes:
  postgres-data:
