version: '3'

services:
  python:
    build:
      context: ./.docker/python/development
      dockerfile: Dockerfile
    container_name: flask-movies
    restart: always
    environment:
      - APP_NAME=movies
      
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_DATABASE_TEST=${DB_DATABASE_TEST}

      - AUTH_URL=${AUTH_URL}
      - AUTH_TOKEN=${AUTH_TOKEN}

      - KINOPOISK_TOKEN=${KINOPOISK_TOKEN}
    networks:
      - movies-net
      - database
  postgres:
    build:
      context: ./.docker/postgres/development
      dockerfile: Dockerfile
    volumes:
      - ./.docker/postgres/development:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: "${DB_DATABASE},${DB_DATABASE_TEST}"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "15432:5432"
    networks:
      - database

volumes:
  postgres-data:

networks:
  movies-net:
    driver: bridge
  database:
